/**
 * Development seed.
 *
 * Создаёт:
 * - Один platform admin
 * - Тестовый tenant "demo" с базовой subscription
 *
 * Запуск: pnpm --filter @pandaclock/db seed
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.warn("🌱 Seeding database...");

  const admin = await prisma.platformAdmin.upsert({
    where: { email: "admin@pandaclock.uz" },
    update: {},
    create: {
      email: "admin@pandaclock.uz",
      // dev-only password: "admin1234" (bcrypt hash will be generated by auth service)
      passwordHash: "$2b$10$placeholder.replace.me.during.dev.setup",
      firstName: "Platform",
      lastName: "Admin",
      role: "SUPER_ADMIN",
    },
  });

  const demo = await prisma.tenant.upsert({
    where: { slug: "demo" },
    update: {},
    create: {
      slug: "demo",
      name: "Demo Company",
      industry: "IT",
      schemaName: "tenant_demo",
      status: "TRIAL",
      trialEndsAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      subscription: {
        create: {
          plan: "STARTER",
          employeesLimit: 10,
          modules: { it: true },
          priceAmount: 0,
          priceCurrency: "UZS",
          billingPeriod: "MONTHLY",
          startedAt: new Date(),
          expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        },
      },
    },
  });

  console.warn(`✓ Platform admin: ${admin.email}`);
  console.warn(`✓ Demo tenant: ${demo.slug} → schema ${demo.schemaName}`);
  console.warn("🌱 Seed complete.");
}

main()
  .catch((e: unknown) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => {
    void prisma.$disconnect();
  });
